title: AESF Homepage
description: >- # this means to ignore newlines until "baseurl:"
  Arbeitsgemeinschaft Empirische Sonderpädagogische Forschung

email: jazznbass98@gmail.com
github_username:  jazznbass

baseurl: /aesf_homepage
#url: http://www.aesf.eu/aesf_homepage   #https://jazznbass.github.io/aesf_homepage

# Build settings
theme: minima

# theme: jekyll-theme-tactile

permalink: /:year/:month/:day/:title:output_ext

plugins:
  - jekyll-feed

markdown: kramdown

# Reading Files
include:
  - _pages
